name: 'Test'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version'
        required: true
        default: 0.67.0
      tracer_url:
        description: 'Url to download the tracer'
        required: true
        default: https://github.com/DataDog/dd-trace-php/releases/download/0.67.0/datadog-php-tracer-0.67.0.x86_64.tar.gz
      profiler_url:
        description: 'Url to download the profiler'
        required: true
        default: https://github.com/labbati/test-actions/releases/download/profiler/datadog-profiling-x86_64-linux.tar.gz
jobs:
  Build-Final-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: chmod a+x ${GITHUB_WORKSPACE}/.github/workflows/generate-final-artifact.sh
      - run: |
              ${GITHUB_WORKSPACE}/.github/workflows/generate-final-artifact.sh \
                ${{ github.event.inputs.version }} \
                ${{ github.event.inputs.tracer_url }} \
                ${{ github.event.inputs.profiler_url }} \
      - name: Archive GNU production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dd-library-php-x86_64-gnu.tar.gz
          path: dd-library-php-x86_64-gnu.tar.gz
      - name: Archive musl production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dd-library-php-x86_64-musl.tar.gz
          path: dd-library-php-x86_64-musl.tar.gz
