name: 'Test'
on:
  workflow_dispatch:
    inputs:
      tracer_url:
        description: 'Url to download the tracer'
        required: true
      profiler_url:
        description: 'Url to download the profiler'
        required: true
jobs:
  Build-Final-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
              ${GITHUB_WORKSPACE}/.github/workflows/generate-final-artifact.sh \
                ${{ github.event.inputs.tracer_url }} \
                ${{ github.event.inputs.profiler_url }} \
      - name: Archive GNU production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dd-library-php-x86_64-gnu.tar.gz
          path: dd-library-php-x86_64-gnu.tar.gz
      - name: Archive musl production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dd-library-php-x86_64-musl.tar.gz
          path: dd-library-php-x86_64-musl.tar.gz
